# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(860, 615)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Title = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Title.setFont(font)
        self.Title.setObjectName("Title")
        self.verticalLayout_2.addWidget(self.Title)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.MplWidget = QtWidgets.QWidget(self.centralwidget)
        self.MplWidget.setMinimumSize(QtCore.QSize(200, 200))
        self.MplWidget.setObjectName("MplWidget")
        self.verticalLayout.addWidget(self.MplWidget)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.inputScal2 = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.inputScal2.setFont(font)
        self.inputScal2.setObjectName("inputScal2")
        self.gridLayout_2.addWidget(self.inputScal2, 2, 1, 1, 1)
        self.labelScal3 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelScal3.setFont(font)
        self.labelScal3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.labelScal3.setObjectName("labelScal3")
        self.gridLayout_2.addWidget(self.labelScal3, 3, 0, 1, 1)
        self.inputScal0 = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.inputScal0.setFont(font)
        self.inputScal0.setObjectName("inputScal0")
        self.gridLayout_2.addWidget(self.inputScal0, 0, 1, 1, 1)
        self.labelScal2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelScal2.setFont(font)
        self.labelScal2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.labelScal2.setObjectName("labelScal2")
        self.gridLayout_2.addWidget(self.labelScal2, 2, 0, 1, 1)
        self.labelScal0 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelScal0.setFont(font)
        self.labelScal0.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.labelScal0.setObjectName("labelScal0")
        self.gridLayout_2.addWidget(self.labelScal0, 0, 0, 1, 1)
        self.inputScal3 = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.inputScal3.setFont(font)
        self.inputScal3.setObjectName("inputScal3")
        self.gridLayout_2.addWidget(self.inputScal3, 3, 1, 1, 1)
        self.labelScal1 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelScal1.setFont(font)
        self.labelScal1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.labelScal1.setObjectName("labelScal1")
        self.gridLayout_2.addWidget(self.labelScal1, 1, 0, 1, 1)
        self.inputScal1 = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.inputScal1.setFont(font)
        self.inputScal1.setObjectName("inputScal1")
        self.gridLayout_2.addWidget(self.inputScal1, 1, 1, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout_2)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.inputOffset2 = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.inputOffset2.setFont(font)
        self.inputOffset2.setObjectName("inputOffset2")
        self.gridLayout_4.addWidget(self.inputOffset2, 2, 1, 1, 1)
        self.labelOffset3 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelOffset3.setFont(font)
        self.labelOffset3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.labelOffset3.setObjectName("labelOffset3")
        self.gridLayout_4.addWidget(self.labelOffset3, 3, 0, 1, 1)
        self.inputOffset0 = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.inputOffset0.setFont(font)
        self.inputOffset0.setObjectName("inputOffset0")
        self.gridLayout_4.addWidget(self.inputOffset0, 0, 1, 1, 1)
        self.labelOffset2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelOffset2.setFont(font)
        self.labelOffset2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.labelOffset2.setObjectName("labelOffset2")
        self.gridLayout_4.addWidget(self.labelOffset2, 2, 0, 1, 1)
        self.labelOffset0 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelOffset0.setFont(font)
        self.labelOffset0.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.labelOffset0.setObjectName("labelOffset0")
        self.gridLayout_4.addWidget(self.labelOffset0, 0, 0, 1, 1)
        self.inputOffset3 = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.inputOffset3.setFont(font)
        self.inputOffset3.setObjectName("inputOffset3")
        self.gridLayout_4.addWidget(self.inputOffset3, 3, 1, 1, 1)
        self.labelOffset1 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelOffset1.setFont(font)
        self.labelOffset1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.labelOffset1.setObjectName("labelOffset1")
        self.gridLayout_4.addWidget(self.labelOffset1, 1, 0, 1, 1)
        self.inputOffset1 = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.inputOffset1.setFont(font)
        self.inputOffset1.setObjectName("inputOffset1")
        self.gridLayout_4.addWidget(self.inputOffset1, 1, 1, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout_4)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout.setStretch(0, 1)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.white_noise = QtWidgets.QRadioButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.white_noise.setFont(font)
        self.white_noise.setObjectName("white_noise")
        self.buttonGroup = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.white_noise)
        self.gridLayout.addWidget(self.white_noise, 14, 1, 1, 1)
        self.labelData1 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelData1.setFont(font)
        self.labelData1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.labelData1.setObjectName("labelData1")
        self.gridLayout.addWidget(self.labelData1, 0, 0, 1, 1)
        self.inputData10 = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.inputData10.setFont(font)
        self.inputData10.setObjectName("inputData10")
        self.gridLayout.addWidget(self.inputData10, 9, 1, 1, 1)
        self.inputData8 = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.inputData8.setFont(font)
        self.inputData8.setObjectName("inputData8")
        self.gridLayout.addWidget(self.inputData8, 7, 1, 1, 1)
        self.labelData9 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelData9.setFont(font)
        self.labelData9.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.labelData9.setObjectName("labelData9")
        self.gridLayout.addWidget(self.labelData9, 8, 0, 1, 1)
        self.inputData1 = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.inputData1.setFont(font)
        self.inputData1.setObjectName("inputData1")
        self.gridLayout.addWidget(self.inputData1, 0, 1, 1, 1)
        self.inputData3 = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.inputData3.setFont(font)
        self.inputData3.setObjectName("inputData3")
        self.gridLayout.addWidget(self.inputData3, 2, 1, 1, 1)
        self.inputData7 = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.inputData7.setFont(font)
        self.inputData7.setObjectName("inputData7")
        self.gridLayout.addWidget(self.inputData7, 6, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(141, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 11, 0, 1, 1)
        self.Fixed_Frequency = QtWidgets.QRadioButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Fixed_Frequency.setFont(font)
        self.Fixed_Frequency.setChecked(False)
        self.Fixed_Frequency.setObjectName("Fixed_Frequency")
        self.buttonGroup.addButton(self.Fixed_Frequency)
        self.gridLayout.addWidget(self.Fixed_Frequency, 12, 0, 1, 1)
        self.Linear_Feedback = QtWidgets.QRadioButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Linear_Feedback.setFont(font)
        self.Linear_Feedback.setObjectName("Linear_Feedback")
        self.buttonGroup.addButton(self.Linear_Feedback)
        self.gridLayout.addWidget(self.Linear_Feedback, 12, 1, 1, 1)
        self.Frequency_Sweep = QtWidgets.QRadioButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Frequency_Sweep.setFont(font)
        self.Frequency_Sweep.setObjectName("Frequency_Sweep")
        self.buttonGroup.addButton(self.Frequency_Sweep)
        self.gridLayout.addWidget(self.Frequency_Sweep, 13, 0, 1, 1)
        self.Parametric_Feedback = QtWidgets.QRadioButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Parametric_Feedback.setFont(font)
        self.Parametric_Feedback.setObjectName("Parametric_Feedback")
        self.buttonGroup.addButton(self.Parametric_Feedback)
        self.gridLayout.addWidget(self.Parametric_Feedback, 13, 1, 1, 1)
        self.labelData3 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelData3.setFont(font)
        self.labelData3.setObjectName("labelData3")
        self.gridLayout.addWidget(self.labelData3, 2, 0, 1, 1)
        self.labelData6 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelData6.setFont(font)
        self.labelData6.setObjectName("labelData6")
        self.gridLayout.addWidget(self.labelData6, 5, 0, 1, 1)
        self.labelData10 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelData10.setFont(font)
        self.labelData10.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.labelData10.setObjectName("labelData10")
        self.gridLayout.addWidget(self.labelData10, 9, 0, 1, 1)
        self.labelData8 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelData8.setFont(font)
        self.labelData8.setObjectName("labelData8")
        self.gridLayout.addWidget(self.labelData8, 7, 0, 1, 1)
        self.labelData7 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelData7.setFont(font)
        self.labelData7.setObjectName("labelData7")
        self.gridLayout.addWidget(self.labelData7, 6, 0, 1, 1)
        self.buttonSend = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.buttonSend.setFont(font)
        self.buttonSend.setObjectName("buttonSend")
        self.gridLayout.addWidget(self.buttonSend, 10, 1, 1, 1)
        self.inputData4 = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.inputData4.setFont(font)
        self.inputData4.setObjectName("inputData4")
        self.gridLayout.addWidget(self.inputData4, 3, 1, 1, 1)
        self.labelData5 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelData5.setFont(font)
        self.labelData5.setObjectName("labelData5")
        self.gridLayout.addWidget(self.labelData5, 4, 0, 1, 1)
        self.labelData2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelData2.setFont(font)
        self.labelData2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.labelData2.setObjectName("labelData2")
        self.gridLayout.addWidget(self.labelData2, 1, 0, 1, 1)
        self.labelData4 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelData4.setFont(font)
        self.labelData4.setObjectName("labelData4")
        self.gridLayout.addWidget(self.labelData4, 3, 0, 1, 1)
        self.inputData2 = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.inputData2.setFont(font)
        self.inputData2.setObjectName("inputData2")
        self.gridLayout.addWidget(self.inputData2, 1, 1, 1, 1)
        self.inputData5 = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.inputData5.setFont(font)
        self.inputData5.setObjectName("inputData5")
        self.gridLayout.addWidget(self.inputData5, 4, 1, 1, 1)
        self.inputData6 = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.inputData6.setFont(font)
        self.inputData6.setObjectName("inputData6")
        self.gridLayout.addWidget(self.inputData6, 5, 1, 1, 1)
        self.inputData9 = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.inputData9.setFont(font)
        self.inputData9.setObjectName("inputData9")
        self.gridLayout.addWidget(self.inputData9, 8, 1, 1, 1)
        self.inputFileName = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.inputFileName.setFont(font)
        self.inputFileName.setObjectName("inputFileName")
        self.gridLayout.addWidget(self.inputFileName, 18, 1, 1, 1)
        self.buttonMeasurement = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.buttonMeasurement.setFont(font)
        self.buttonMeasurement.setObjectName("buttonMeasurement")
        self.gridLayout.addWidget(self.buttonMeasurement, 16, 1, 1, 1)
        self.A_x_plus_b = QtWidgets.QRadioButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.A_x_plus_b.setFont(font)
        self.A_x_plus_b.setObjectName("A_x_plus_b")
        self.buttonGroup.addButton(self.A_x_plus_b)
        self.gridLayout.addWidget(self.A_x_plus_b, 14, 0, 1, 1)
        self.checkBoxStore = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBoxStore.setFont(font)
        self.checkBoxStore.setObjectName("checkBoxStore")
        self.gridLayout.addWidget(self.checkBoxStore, 17, 0, 1, 1)
        self.labelFileName = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelFileName.setFont(font)
        self.labelFileName.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.labelFileName.setObjectName("labelFileName")
        self.gridLayout.addWidget(self.labelFileName, 18, 0, 1, 1)
        self.polynomial = QtWidgets.QRadioButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.polynomial.setFont(font)
        self.polynomial.setObjectName("polynomial")
        self.buttonGroup.addButton(self.polynomial)
        self.gridLayout.addWidget(self.polynomial, 15, 0, 1, 1)
        self.CBC = QtWidgets.QRadioButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.CBC.setFont(font)
        self.CBC.setObjectName("CBC")
        self.buttonGroup.addButton(self.CBC)
        self.gridLayout.addWidget(self.CBC, 15, 1, 1, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout)
        self.horizontalLayout_2.setStretch(0, 1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.inputData1, self.inputData2)
        MainWindow.setTabOrder(self.inputData2, self.inputData3)
        MainWindow.setTabOrder(self.inputData3, self.inputData4)
        MainWindow.setTabOrder(self.inputData4, self.inputData5)
        MainWindow.setTabOrder(self.inputData5, self.inputData6)
        MainWindow.setTabOrder(self.inputData6, self.inputData7)
        MainWindow.setTabOrder(self.inputData7, self.inputData8)
        MainWindow.setTabOrder(self.inputData8, self.inputData9)
        MainWindow.setTabOrder(self.inputData9, self.inputData10)
        MainWindow.setTabOrder(self.inputData10, self.buttonSend)
        MainWindow.setTabOrder(self.buttonSend, self.Fixed_Frequency)
        MainWindow.setTabOrder(self.Fixed_Frequency, self.Linear_Feedback)
        MainWindow.setTabOrder(self.Linear_Feedback, self.Frequency_Sweep)
        MainWindow.setTabOrder(self.Frequency_Sweep, self.Parametric_Feedback)
        MainWindow.setTabOrder(self.Parametric_Feedback, self.A_x_plus_b)
        MainWindow.setTabOrder(self.A_x_plus_b, self.white_noise)
        MainWindow.setTabOrder(self.white_noise, self.polynomial)
        MainWindow.setTabOrder(self.polynomial, self.CBC)
        MainWindow.setTabOrder(self.CBC, self.buttonMeasurement)
        MainWindow.setTabOrder(self.buttonMeasurement, self.checkBoxStore)
        MainWindow.setTabOrder(self.checkBoxStore, self.inputFileName)
        MainWindow.setTabOrder(self.inputFileName, self.inputScal0)
        MainWindow.setTabOrder(self.inputScal0, self.inputScal1)
        MainWindow.setTabOrder(self.inputScal1, self.inputScal2)
        MainWindow.setTabOrder(self.inputScal2, self.inputScal3)
        MainWindow.setTabOrder(self.inputScal3, self.inputOffset0)
        MainWindow.setTabOrder(self.inputOffset0, self.inputOffset1)
        MainWindow.setTabOrder(self.inputOffset1, self.inputOffset2)
        MainWindow.setTabOrder(self.inputOffset2, self.inputOffset3)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Title.setText(_translate("MainWindow", "RedPitaya Cantilever Controller"))
        self.inputScal2.setText(_translate("MainWindow", "1"))
        self.labelScal3.setText(_translate("MainWindow", "Scaling OUT 2"))
        self.inputScal0.setText(_translate("MainWindow", "1"))
        self.labelScal2.setText(_translate("MainWindow", "Scaling OUT 1"))
        self.labelScal0.setText(_translate("MainWindow", "Scaling IN 1"))
        self.inputScal3.setText(_translate("MainWindow", "1"))
        self.labelScal1.setText(_translate("MainWindow", "Scaling IN 2"))
        self.inputScal1.setText(_translate("MainWindow", "1"))
        self.inputOffset2.setText(_translate("MainWindow", "0"))
        self.labelOffset3.setText(_translate("MainWindow", "Offset OUT 2"))
        self.inputOffset0.setText(_translate("MainWindow", "0"))
        self.labelOffset2.setText(_translate("MainWindow", "Offset OUT 1"))
        self.labelOffset0.setText(_translate("MainWindow", "Offset IN 1"))
        self.inputOffset3.setText(_translate("MainWindow", "0"))
        self.labelOffset1.setText(_translate("MainWindow", "Offset IN 2"))
        self.inputOffset1.setText(_translate("MainWindow", "0"))
        self.white_noise.setText(_translate("MainWindow", "White noise"))
        self.labelData1.setText(_translate("MainWindow", "Frequency Out [Hz]"))
        self.inputData10.setText(_translate("MainWindow", "100000"))
        self.inputData8.setText(_translate("MainWindow", "0"))
        self.labelData9.setText(_translate("MainWindow", "Number of Samples"))
        self.inputData1.setText(_translate("MainWindow", "5"))
        self.inputData3.setText(_translate("MainWindow", "0"))
        self.inputData7.setText(_translate("MainWindow", "0"))
        self.Fixed_Frequency.setText(_translate("MainWindow", "Fixed Frequency"))
        self.Linear_Feedback.setText(_translate("MainWindow", "Linear Feedback"))
        self.Frequency_Sweep.setText(_translate("MainWindow", "Frequency Sweep"))
        self.Parametric_Feedback.setText(_translate("MainWindow", "Parametric Feedback"))
        self.labelData3.setText(_translate("MainWindow", "Param3"))
        self.labelData6.setText(_translate("MainWindow", "Param6"))
        self.labelData10.setText(_translate("MainWindow", "Sampling Frequenzy [Hz]"))
        self.labelData8.setText(_translate("MainWindow", "Param8"))
        self.labelData7.setText(_translate("MainWindow", "Param7"))
        self.buttonSend.setText(_translate("MainWindow", "Send Data"))
        self.inputData4.setText(_translate("MainWindow", "0"))
        self.labelData5.setText(_translate("MainWindow", "Param5"))
        self.labelData2.setText(_translate("MainWindow", "Amplitude Out [mV]"))
        self.labelData4.setText(_translate("MainWindow", "Param4"))
        self.inputData2.setText(_translate("MainWindow", "100"))
        self.inputData5.setText(_translate("MainWindow", "0"))
        self.inputData6.setText(_translate("MainWindow", "0"))
        self.inputData9.setText(_translate("MainWindow", "100000"))
        self.inputFileName.setText(_translate("MainWindow", "Data"))
        self.buttonMeasurement.setText(_translate("MainWindow", "Start Measurement"))
        self.A_x_plus_b.setText(_translate("MainWindow", "Ax + b"))
        self.checkBoxStore.setText(_translate("MainWindow", "Store to *.csv"))
        self.labelFileName.setText(_translate("MainWindow", "File Name"))
        self.polynomial.setText(_translate("MainWindow", "Arbitrary Polynomial"))
        self.CBC.setText(_translate("MainWindow", "CBC (coming soon)"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

